obsrvr :
  location_model : "mahdiiiii04/obsrvr-locator"
  inventory_model : "MoncefAn/inventory/inventory_t5_model_v3"
  surroundings_model : "YasserSai001/surroundings-detector"
  tokenizer_model : "t5-small"
cn:
  concept_net_file : "CNData/filtered_triples.json"
env:
  rom_file : "ROMS/zork1.z5"
  node_mapping_file : "mapping/zork1_node2id.json"
actor:
  embedding_model : "bert-base-uncased"
  tokenizer_model : "bert-base-uncased"
train:
  max_nodes : 10000
  feat_dim : 256
  hidden_dim : 256
  repr_dim : 256
  latent_dim : 128
  beta_start : 0.01
  beta_end : 0.05
  epsilon_start : 0.1
  epsilon_end : 0.001
  learning_rate : 0.0003
  batch_size : 32
  buffer_capacity : 10000
  replay_frequency : 4
  device : "cuda"
  hf_repo: "mahdiiiii04/ibkg"